using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using NIOSH_MineCreation;

public class MineCreator : MonoBehaviour
{
    public LoadableAssetManager LoadableAssetManager;

    public Transform AssetCollection;

    private MineBuilder builder;

    public MineSettings.TileSet tileSet;
    public LoadableAssetCollection autoGeneratedAssets;

    //public MineTilesetCollection collection;

    public int rockDustLvl;

    public int numEntries;

    public int numCrosscuts;

    public float seamHeight;

    public float pillarWidth;

    public float pillarLength;

    public float entryWidth;

    public float BoltSpacing = 1.22f;

    public static MineCreator GetDefault()
    {
        return Util.GetDefaultManager<MineCreator>(null, "MineCreator", false);
    }

    private void Start()
    {
        if (LoadableAssetManager == null)
            LoadableAssetManager = LoadableAssetManager.GetDefault(gameObject);

        builder = new MineBuilder();
    }

    public void GenerateMine()
    {
        Debug.Log("GenerateMine");
        MineSettings newSettings = new MineSettings(tileSet, 0, numEntries, numCrosscuts, seamHeight, pillarWidth, pillarLength, entryWidth, BoltSpacing, 1.067f, false);

        StartCoroutine(builder.BuildMine(LoadableAssetManager.GetMineTileset(tileSet), autoGeneratedAssets,newSettings, AssetCollection));
    }

    public List<RoofBoltGenerator> GetRoofboltGeneratorZones()
    {
        return builder.SpawnedRoofBoltGenerators;
    }

    public MineBuilder GetBuilderRef()
    {
        return builder;
    }
}
